### ISSUE TITLE
test

### ISSUE THREAD

**Issue by anoadragon453** [anoadragon453/matrix#1]
@imachug Not sure how else to contact you, but heads up that my matrix server is back up. You'll need to sign out of your existing session and put https://matrix.amorgan.xyz instead of https://amorgan.xyz as your homeserver.

Your existing username and password will still work.

If you can't sign out for some reason, let me know.

**Comment by purplesyringa** [comment]
Thanks for notifying, I'll try to log on now.

**Comment by purplesyringa** [comment]
It works, thanks.
